language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-frontend 1512582/udagram-frontend:v6
  - docker tag udagram-api-feed 1512582/udagram-api-feed:latest
  - docker tag udagram-api-user 1512582/udagram-api-user:latest
  - docker tag reverseproxy 1512582/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 1512582/udagram-frontend
  - docker push 1512582/udagram-api-feed
  - docker push 1512582/udagram-api-user
  - docker push 1512582/reverseproxy